version: "3.9"
services:
  mysql:
    image: mysql:latest
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: root456789
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: jungle
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    entrypoint: ["/app/waitfor.sh", "mysql:3306", "--", "/app/start.sh"]
    command: ["/app/main"]
volumes:
  dbdata:
