// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
)

type Clothe struct {
	ID         int32        `json:"id"`
	Name       string       `json:"name"`
	Amount     int32        `json:"amount"`
	Cost       int32        `json:"cost"`
	Price      int32        `json:"price"`
	CreateTime sql.NullTime `json:"create_time"`
}

type User struct {
	Uuid       string       `json:"uuid"`
	Name       string       `json:"name"`
	Email      string       `json:"email"`
	Password   string       `json:"password"`
	CreateTime sql.NullTime `json:"create_time"`
}
