name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 049366755955.dkr.ecr.us-west-2.amazonaws.com

      - name: Push Docker Image to ECR
        run: |
          docker build -t jungle .
          docker tag jungle:latest 049366755955.dkr.ecr.us-west-2.amazonaws.com/jungle:latest
          docker push 049366755955.dkr.ecr.us-west-2.amazonaws.com/jungle:latest

      - name: ECR Cleanup
        run: aws ecr batch-delete-image --repository-name jungle --image-ids imageTag=latest imageTag=-
# jobs:
#   build:
#     runs-on: self-hosted

#     steps:
#       - name: Pull docker image
#         run: docker pull benpeng/jungle:latest

#       - name: Delete old docker container
#         run: docker rm -f myapp || true

#       - name: Run docker container
#         run: docker run -d --name myapp -p 3000:3000 benpeng/jungle:latest
