name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull docker image
        run: docker pull benpeng/jungle:latest

      - name: Check if Docker Compose is running
        id: check-compose
        run: |
          if docker-compose ps -q; then
            echo "::set-output name=compose-running::true"
          else
            echo "::set-output name=compose-running::false"
          fi

      - name: Stop Docker Compose
        if: steps.check-compose.outputs.compose-running == 'true'
        run: |
          docker-compose down

      - name: Run Docker Compose
        run: docker compose up -d

      - name: Check Docker Images and remove
        run: |
          # 列出所有 "dangling" 或 "none" image
          docker images -q --filter "dangling=true" | xargs -r docker rmi
        if: success() # 僅在上述步驟成功時執行
