name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Write app.env
        env:
          PORT: ${{ secrets.ENV_PORT }}
          DB_DRIVER: ${{ secrets.ENV_DB_DRIVER }}
          DB_SOURCE: ${{ secrets.ENV_DB_SOURCE }}
        run: |
          touch app.env
          echo PORT=3000 >> app.env
          echo DB_DRIVER=mysql >> app.env
          echo DB_SOURCE=root:root456789@tcp(mysql8:3306)/jungle?multiStatements=true >> app.env

      - name: Build Docker image
        run: |
          docker build -t benpeng/jungle .
          docker push benpeng/jungle
